/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectofinal;

import com.utp.ejercicio1.Cola;
import com.utp.ejercicio2.Pila;
import com.utp.ejercicio3.Cola3;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jyarango
 */
public class Global extends javax.swing.JFrame {

    /**
     * Creates new form Global
     */
    public Global() {
        initComponents();
        this.setLocationRelativeTo(null);
        dtmEjercicio1 = (DefaultTableModel) dtm1.getModel();
        dtmEjercicio2 = (DefaultTableModel) dtm2.getModel();
        dtmEjercicio3 = (DefaultTableModel) dtm3.getModel();
        //Radiobutton Ejercicio3
        btg = new ButtonGroup();
        btg.add(rbaux);
        btg.add(rbobs);
        btg.add(rbmed);
        btg.add(rbcir);
        txtgastoTrabajadores.setText(String.valueOf(cola3.gastoTrabajadores()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtid1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtnombres1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtapellidos1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtdni1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txttelefono1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtcorreo1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtdireccion1 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        btnIngresar1 = new javax.swing.JButton();
        btnPeek1 = new javax.swing.JButton();
        btnVer1 = new javax.swing.JButton();
        btnPoll1 = new javax.swing.JButton();
        btnEliminar1 = new javax.swing.JButton();
        btningAuto1 = new javax.swing.JButton();
        btnBuscar1 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        dtm1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        btnIngresar2 = new javax.swing.JButton();
        btnPeek2 = new javax.swing.JButton();
        btnPop2 = new javax.swing.JButton();
        btnBuscar2 = new javax.swing.JButton();
        btnVer2 = new javax.swing.JButton();
        btningAuto2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtid2 = new javax.swing.JTextField();
        txtnombres2 = new javax.swing.JTextField();
        txtapellidos2 = new javax.swing.JTextField();
        txtcorreo2 = new javax.swing.JTextField();
        txtdni2 = new javax.swing.JTextField();
        txttelefono2 = new javax.swing.JTextField();
        txthistoria2 = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        dtm2 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        txtnombres = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        rbaux = new javax.swing.JRadioButton();
        rbobs = new javax.swing.JRadioButton();
        rbmed = new javax.swing.JRadioButton();
        rbcir = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        txthoras = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        btnIngresar3 = new javax.swing.JButton();
        btnPeek3 = new javax.swing.JButton();
        btnPoll3 = new javax.swing.JButton();
        btnBuscar3 = new javax.swing.JButton();
        btnEliminar3 = new javax.swing.JButton();
        btningAuto3 = new javax.swing.JButton();
        btnMayor3 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        txtgastoTrabajadores = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        dtm3 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("EJERCICIO 1: COLA DINÁMICA CON OBJETO");

        jLabel2.setText("ID");

        jLabel3.setText("Nombres");

        jLabel4.setText("Apellidos");

        jLabel5.setText("DNI");

        jLabel6.setText("Telefono");

        jLabel7.setText("Correo");

        jLabel8.setText("Direccion");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txtcorreo1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtdireccion1))
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtid1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtdni1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txttelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtnombres1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txtapellidos1)
                                .addContainerGap())))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtid1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnombres1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtapellidos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdni1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcorreo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdireccion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnIngresar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar.png"))); // NOI18N
        btnIngresar1.setText("INGRESAR CLIENTE A COLA");
        btnIngresar1.setToolTipText("");
        btnIngresar1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnIngresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresar1ActionPerformed(evt);
            }
        });

        btnPeek1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user.png"))); // NOI18N
        btnPeek1.setText("PRIMER CLIENTE EN COLA");
        btnPeek1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPeek1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeek1ActionPerformed(evt);
            }
        });

        btnVer1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cola.png"))); // NOI18N
        btnVer1.setText("MOSTRAR CANTIDAD CLIENTES");
        btnVer1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnVer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVer1ActionPerformed(evt);
            }
        });

        btnPoll1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        btnPoll1.setText("RETIRAR CLIENTE ATENDIDO");
        btnPoll1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPoll1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPoll1ActionPerformed(evt);
            }
        });

        btnEliminar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminarSpecial.png"))); // NOI18N
        btnEliminar1.setText("CLIENTE ABANDONA COLA");
        btnEliminar1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar1ActionPerformed(evt);
            }
        });

        btningAuto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/data.png"))); // NOI18N
        btningAuto1.setText("DATA DEMO PARA TEST");
        btningAuto1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btningAuto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btningAuto1ActionPerformed(evt);
            }
        });

        btnBuscar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        btnBuscar1.setText("BUSCAR CLIENTE EN COLA");
        btnBuscar1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnPoll1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btningAuto1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnIngresar1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnVer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnPeek1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngresar1)
                    .addComponent(btnVer1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPeek1)
                    .addComponent(btnEliminar1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btningAuto1)
                    .addComponent(btnPoll1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscar1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dtm1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombres", "Apellidos", "DNI", "Telefono", "Correo", "Direccion"
            }
        ));
        jScrollPane5.setViewportView(dtm1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 806, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 166, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );

        jTabbedPane4.addTab("Ejercicio1", jPanel1);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("EJERCICIO 2: PILA ESTÁTICA CON OBJETO");

        btnIngresar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar.png"))); // NOI18N
        btnIngresar2.setText("INGRESAR PACIENTE A PILA");
        btnIngresar2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnIngresar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresar2ActionPerformed(evt);
            }
        });

        btnPeek2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user.png"))); // NOI18N
        btnPeek2.setText("ÚLTIMO PACIENTE EN PILA");
        btnPeek2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPeek2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeek2ActionPerformed(evt);
            }
        });

        btnPop2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        btnPop2.setText("RETIRAR PACIENTE DE PILA");
        btnPop2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPop2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPop2ActionPerformed(evt);
            }
        });

        btnBuscar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        btnBuscar2.setText("BUSCAR PACIENTE DNI");
        btnBuscar2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnBuscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar2ActionPerformed(evt);
            }
        });

        btnVer2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pila.png"))); // NOI18N
        btnVer2.setText("CANTIDAD DE PACIENTES");
        btnVer2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnVer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVer2ActionPerformed(evt);
            }
        });

        btningAuto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/data.png"))); // NOI18N
        btningAuto2.setText("DATA DEMO PARA TEST");
        btningAuto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btningAuto2ActionPerformed(evt);
            }
        });

        jLabel10.setText("ID");

        jLabel11.setText("Nombres");

        jLabel12.setText("Apellidos");

        jLabel13.setText("Correo");

        jLabel14.setText("DNI");

        jLabel15.setText("Telefono");

        jLabel16.setText("Historia");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel10)
                        .addComponent(jLabel11)
                        .addComponent(jLabel12))
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtcorreo2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtapellidos2)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txthistoria2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(txtid2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)))
                        .addComponent(txtdni2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txttelefono2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtnombres2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnombres2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtapellidos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtid2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcorreo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdni2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttelefono2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txthistoria2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btningAuto2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVer2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPop2)
                    .addComponent(btnPeek2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIngresar2))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(btnIngresar2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPeek2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPop2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVer2))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btningAuto2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dtm2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombres", "Apellidos", "Correo", "DNI", "Telefono", "Historia"
            }
        ));
        jScrollPane6.setViewportView(dtm2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(331, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(270, 270, 270))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Ejercicio2", jPanel2);

        jLabel17.setText("Nombres del trabajador");

        jLabel18.setText("Tipo de trabajador");

        rbaux.setText("Auxiliar");

        rbobs.setText("Obstetra");

        rbmed.setText("Medico");

        rbcir.setText("Cirujano");

        jLabel19.setText("Horas laboradas (semana)");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(rbaux)
                                .addComponent(rbobs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rbmed)
                                .addComponent(rbcir))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(txtnombres, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(txthoras, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtnombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(rbaux))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbobs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbmed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbcir)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txthoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        btnIngresar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar.png"))); // NOI18N
        btnIngresar3.setText("INGRESAR TRABAJADOR A COLA");
        btnIngresar3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnIngresar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresar3ActionPerformed(evt);
            }
        });

        btnPeek3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user.png"))); // NOI18N
        btnPeek3.setText("PRIMER TRABAJADOR EN COLA");
        btnPeek3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPeek3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeek3ActionPerformed(evt);
            }
        });

        btnPoll3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        btnPoll3.setText("RETIRAR TRABAJADOR ATENDIDO");
        btnPoll3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPoll3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPoll3ActionPerformed(evt);
            }
        });

        btnBuscar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        btnBuscar3.setText("BUSCAR TRABAJADOR EN COLA");
        btnBuscar3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnBuscar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar3ActionPerformed(evt);
            }
        });

        btnEliminar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminarSpecial.png"))); // NOI18N
        btnEliminar3.setText("RETIRAR TRABAJADOR DE COLA");
        btnEliminar3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEliminar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar3ActionPerformed(evt);
            }
        });

        btningAuto3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/data.png"))); // NOI18N
        btningAuto3.setText("DATA DEMO PARA TEST");
        btningAuto3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btningAuto3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btningAuto3ActionPerformed(evt);
            }
        });

        btnMayor3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mayorSueldo.png"))); // NOI18N
        btnMayor3.setText("TRABAJADOR CON MAYOR SUELDO");
        btnMayor3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMayor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMayor3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPoll3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPeek3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIngresar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuscar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMayor3)
                    .addComponent(btningAuto3, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar3, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngresar3)
                    .addComponent(btnMayor3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPeek3)
                    .addComponent(btnEliminar3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPoll3)
                    .addComponent(btningAuto3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscar3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("EJERCICIO 3: COLA DINÁMICA CON OBJETO");

        txtgastoTrabajadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgastoTrabajadoresActionPerformed(evt);
            }
        });

        jLabel21.setText("Total a pagar");

        dtm3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Tipo", "Horas laboradas", "Sueldo"
            }
        ));
        jScrollPane7.setViewportView(dtm3);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jLabel20))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(txtgastoTrabajadores, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(txtgastoTrabajadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Ejercicio3", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane4)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane4)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    com.utp.ejercicio1.Cola cola1 = new Cola();
    com.utp.ejercicio3.Cola3 cola3 = new Cola3();
    com.utp.ejercicio2.Pila pila = new Pila(10);
    ButtonGroup btg;
    int tipoGlobal;
    static DefaultTableModel dtmEjercicio1;
    static DefaultTableModel dtmEjercicio2;
    static DefaultTableModel dtmEjercicio3;

    public void ingresarAutomatico2() {
        //pila.push(id, nombres, apellidos, correo, dni, telefono, historia);
        pila.push(1, "Rody", "Fernandez Delgado", "rody@gmail.com", 11111111, 999999999, 111222);
        pila.push(2, "Elias", "Valderrama De la Cruz", "elias@gmail.com", 22222222, 989999999, 222333);
        pila.push(3, "Jorge", "Yarango Villanueva", "jorge@gmail.com", 33333333, 979999999, 333444);
        pila.push(4, "Ruben", "Meza Fernandez", "ruben@gmail.com", 44444444, 969999999, 444555);
        pila.push(5, "Cristhian", "Carbonero Chupayo", "cristhian@gmail.com", 55555555, 959999999, 555666);
    }

    public void ingresarAutomatico() {
        cola1.offer(1, "Rody", "Fernandez Delgado", 11111111, 999999999, "rody@gmail.com", "direccion1");
        cola1.offer(2, "Elias", "Valderrama De la Cruz", 22222222, 989999999, "elias@gmail.com", "direccion2");
        cola1.offer(3, "Jorge", "Yarango Villanueva", 33333333, 979999999, "jorge@gmail.com", "direccion3");
        cola1.offer(4, "Ruben", "Meza Fernandez", 44444444, 969999999, "ruben@gmail.com", "direccion4");
        cola1.offer(5, "Cristhian", "Carbonero Chupayo", 55555555, 959999999, "cristhian@gmail.com", "direccion5");
    }

    public void ingresarAutomatico3() {
        //String nombre, int tipo, int horas
        cola3.offer("Rody", 1, 50);
        cola3.offer("Elias", 2, 20);
        cola3.offer("Jorge", 3, 10);
        cola3.offer("Ruben", 4, 59);
        cola3.offer("Cristhian", 1, 60);
    }

    private void btnIngresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresar1ActionPerformed
        int verificar = 0, dniC = 0, telefonoC = 0, idC = 0;
        if (!txtid1.getText().isEmpty()) {
            idC++;
        }
        if (!txtnombres1.getText().isEmpty()) {
            verificar++;
        }
        if (!txtapellidos1.getText().isEmpty()) {
            verificar++;
        }
        if (!txtdni1.getText().isEmpty() && txtdni1.getText().length() == 8) {
            dniC++;
        }
        if (!txttelefono1.getText().isEmpty() && txttelefono1.getText().length() == 9 && txttelefono1.getText().charAt(0) == '9') {
            telefonoC++;
        }
        if (!txtcorreo1.getText().isEmpty()) {
            verificar++;
        }
        if (!txtdireccion1.getText().isEmpty()) {
            verificar++;
        }

        if (idC == 0) {
            JOptionPane.showMessageDialog(null, "Error, falta ingresar ID.", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtid1.requestFocus();
        } else if (dniC == 0) {
            JOptionPane.showMessageDialog(null, "Error en DNI debe tener 8 digitos.", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtdni1.requestFocus();
        } else if (telefonoC == 0) {
            JOptionPane.showMessageDialog(null, "Error en Telefono debe tener 9 numeros que inicie en 9", "ERROR", JOptionPane.ERROR_MESSAGE);
            txttelefono1.requestFocus();
        } else if (verificar != 4) {
            JOptionPane.showMessageDialog(null, "Faltan datos a ingresar", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Datos validados", "CONFORME", JOptionPane.INFORMATION_MESSAGE);
            //btnIngresar.setEnabled(true);
            int id = Integer.parseInt(txtid1.getText());
            String nombres = txtnombres1.getText();
            String apellidos = txtapellidos1.getText();
            int dni = Integer.parseInt(txtdni1.getText());
            int telefono = Integer.parseInt(txttelefono1.getText());
            String correo = txtcorreo1.getText();
            String direccion = txtdireccion1.getText();
            cola1.offer(id, nombres, apellidos, dni, telefono, correo, direccion);
            //Para ingresar en tabla
            verTabla1(dtmEjercicio1);
            txtid1.setText("");
            txtnombres1.setText("");
            txtapellidos1.setText("");
            txtdni1.setText("");
            txttelefono1.setText("");
            txtcorreo1.setText("");
            txtdireccion1.setText("");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresar1ActionPerformed

    private void btnPeek1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeek1ActionPerformed
        cola1.peek();  // TODO add your handling code here:
    }//GEN-LAST:event_btnPeek1ActionPerformed

    private void btnVer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVer1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "El tamaño actual de la cola es: " + cola1.size(), "TAMAÑO DE LA COLA", JOptionPane.NO_OPTION);
    }//GEN-LAST:event_btnVer1ActionPerformed

    private void btnPoll1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPoll1ActionPerformed
        cola1.poll();
        verTabla1(dtmEjercicio1);

        //  txtAClientes.setText(cola1.print());// TODO add your handling code here:
    }//GEN-LAST:event_btnPoll1ActionPerformed

    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar1ActionPerformed
        // TODO add your handling code here:
        String nombre = JOptionPane.showInputDialog(null, "Introduce el nombre del cliente.", "ELIMINAR CLIENTE", JOptionPane.INFORMATION_MESSAGE);
        cola1.pollSpecial(nombre);
        verTabla1(dtmEjercicio1);

//        txtAClientes.setText(cola1.print());
    }//GEN-LAST:event_btnEliminar1ActionPerformed

    private void btningAuto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btningAuto1ActionPerformed
        // TODO add your handling code here:
        ingresarAutomatico();
        verTabla1(dtmEjercicio1);
        // txtAClientes.setText(cola1.print());
    }//GEN-LAST:event_btningAuto1ActionPerformed

    private void btnBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar1ActionPerformed
        // TODO add your handling code here:
        String nombre = JOptionPane.showInputDialog(null, "Introduce el nombre del cliente.", "BUSQUEDA DE CLIENTE", JOptionPane.INFORMATION_MESSAGE);
        cola1.search(nombre);
    }//GEN-LAST:event_btnBuscar1ActionPerformed

    private int tipo(int radio) {
        tipoGlobal = radio;
        return tipoGlobal;
    }

    private void verTabla3(DefaultTableModel dtm) {
        int fila = dtm.getRowCount();
        for (int f = 0; f < fila; f++) {
            dtm.removeRow(0);
        }
        if (cola3.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Cola vacia", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        cola3.lista(dtmEjercicio3);
    }

    private void verTabla2(DefaultTableModel dtm) {
        int fila = dtm.getRowCount();
        for (int f = 0; f < fila; f++) {
            dtm.removeRow(0);
        }
        if (pila.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Cola vacia", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        pila.lista(dtmEjercicio2);
    }

    private void verTabla1(DefaultTableModel dtm) {
        int fila = dtm.getRowCount();
        for (int f = 0; f < fila; f++) {
            dtm.removeRow(0);
        }
        if (cola1.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Cola vacia", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        cola1.lista(dtmEjercicio1);
    }
    private void btningAuto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btningAuto2ActionPerformed
        // TODO add your handling code here:
        ingresarAutomatico2();
        verTabla2(dtmEjercicio2);
        //txtAPacientes.setText(pila.print());
    }//GEN-LAST:event_btningAuto2ActionPerformed

    private void btnVer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVer2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "El tamaño actual de la pila es: " + pila.size(), "TAMAÑO DE LA pila", JOptionPane.NO_OPTION);
    }//GEN-LAST:event_btnVer2ActionPerformed

    private void btnBuscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar2ActionPerformed
        // TODO add your handling code here:
        int dni = Integer.parseInt(JOptionPane.showInputDialog(null, "Introduce el DNI del paciente.", "BUSQUEDA DE PACIENTE", JOptionPane.INFORMATION_MESSAGE));
        pila.search(dni);
    }//GEN-LAST:event_btnBuscar2ActionPerformed

    private void btnPop2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPop2ActionPerformed
        pila.pop();
        verTabla2(dtmEjercicio2);

        //txtAPacientes.setText(pila.print());// TODO add your handling code here:
    }//GEN-LAST:event_btnPop2ActionPerformed

    private void btnPeek2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeek2ActionPerformed
        pila.peek();  // TODO add your handling code here:
    }//GEN-LAST:event_btnPeek2ActionPerformed

    private void btnIngresar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresar2ActionPerformed

        // TODO add your handling code here:
        int verificar = 0, dniC = 0, telefonoC = 0, historiaC = 0, idC = 0;
        if (!txtid2.getText().isEmpty()) {
            idC++;
        }
        if (!txtnombres2.getText().isEmpty()) {
            verificar++;
        }
        if (!txtapellidos2.getText().isEmpty()) {
            verificar++;
        }
        if (!txtdni2.getText().isEmpty() && txtdni2.getText().length() == 8) {
            dniC++;
        }
        if (!txttelefono2.getText().isEmpty() && txttelefono2.getText().length() == 9 && txttelefono2.getText().charAt(0) == '9') {
            telefonoC++;
        }
        if (!txtcorreo2.getText().isEmpty()) {
            verificar++;
        }
        if (!txthistoria2.getText().isEmpty() && txthistoria2.getText().length() == 4) {
            historiaC++;
        }

        if (idC == 0) {
            JOptionPane.showMessageDialog(null, "Error falta ingresar ID", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtid2.requestFocus();
        } else if (verificar != 3) {
            JOptionPane.showMessageDialog(null, "Faltan datos a ingresar", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else if (dniC == 0) {
            JOptionPane.showMessageDialog(null, "Error en DNI debe tener 8 digitos.", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtdni2.requestFocus();
        } else if (telefonoC == 0) {
            JOptionPane.showMessageDialog(null, "Error en Telefono debe tener 9 numeros que inicie en 9", "ERROR", JOptionPane.ERROR_MESSAGE);
            txttelefono2.requestFocus();
        } else if (historiaC == 0) {
            JOptionPane.showMessageDialog(null, "Error en la historia, debe ser mayor que 0 de 4 cifras", "ERROR", JOptionPane.ERROR_MESSAGE);
            txthistoria2.requestFocus();
        } else {
            JOptionPane.showMessageDialog(null, "Datos validados", "CONFORME", JOptionPane.INFORMATION_MESSAGE);
            int id = Integer.parseInt(txtid2.getText());
            String nombres = txtnombres2.getText();
            String apellidos = txtapellidos2.getText();
            int dni = Integer.parseInt(txtdni2.getText());
            int telefono = Integer.parseInt(txttelefono2.getText());
            String correo = txtcorreo2.getText();
            int historia = Integer.parseInt(txthistoria2.getText());
            pila.push(id, nombres, apellidos, correo, dni, telefono, historia);
            verTabla2(dtmEjercicio2);
            //txtAPacientes.setText(pila.print());
            // btnIngresar.setEnabled(false);
            txtid2.setText("");
            txtnombres2.setText("");
            txtapellidos2.setText("");
            txtdni2.setText("");
            txttelefono2.setText("");
            txtcorreo2.setText("");
            txthistoria2.setText("");
            //btnIngresar.setEnabled(true);
        }
    }//GEN-LAST:event_btnIngresar2ActionPerformed

    private void txtgastoTrabajadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgastoTrabajadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgastoTrabajadoresActionPerformed

    private void btnMayor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMayor3ActionPerformed
        // TODO add your handling code here:
        cola3.mayorSueldo();
    }//GEN-LAST:event_btnMayor3ActionPerformed

    private void btningAuto3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btningAuto3ActionPerformed
        // TODO add your handling code here:
        ingresarAutomatico3();
        verTabla3(dtmEjercicio3);

        // txtATrabajadores.setText(cola3.print());
        txtgastoTrabajadores.setText(String.valueOf(cola3.gastoTrabajadores()));
    }//GEN-LAST:event_btningAuto3ActionPerformed

    private void btnEliminar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar3ActionPerformed
        // TODO add your handling code here:
        String nombre = JOptionPane.showInputDialog(null, "Introduce el nombre del cliente.", "ELIMINAR CLIENTE", JOptionPane.INFORMATION_MESSAGE);
        cola3.pollSpecial(nombre);
        verTabla3(dtmEjercicio3);
        txtgastoTrabajadores.setText(String.valueOf(cola3.gastoTrabajadores()));

        //txtATrabajadores.setText(cola3.print());
    }//GEN-LAST:event_btnEliminar3ActionPerformed

    private void btnBuscar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar3ActionPerformed
        // TODO add your handling code here:
        String nombre = JOptionPane.showInputDialog(null, "Introduce el nombre del cliente.", "BUSQUEDA DE CLIENTE", JOptionPane.INFORMATION_MESSAGE);
        cola3.search(nombre);
    }//GEN-LAST:event_btnBuscar3ActionPerformed

    private void btnPoll3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPoll3ActionPerformed
        cola3.poll();
        verTabla3(dtmEjercicio3);
        txtgastoTrabajadores.setText(String.valueOf(cola3.gastoTrabajadores()));
        //txtATrabajadores.setText(cola3.print());// TODO add your handling code here:
    }//GEN-LAST:event_btnPoll3ActionPerformed

    private void btnPeek3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeek3ActionPerformed
        cola3.peek();  // TODO add your handling code here:
    }//GEN-LAST:event_btnPeek3ActionPerformed

    private void btnIngresar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresar3ActionPerformed

        // TODO add your handling code here:
        int verificar = 0, tipo = 0, horasT = 0;
        if (!txtnombres.getText().isEmpty()) {
            verificar++;
        }
        if (rbaux.isSelected()) {
            tipo(1);
        } else if (rbobs.isSelected()) {
            tipo(2);
        } else if (rbmed.isSelected()) {
            tipo(3);
        } else if (rbcir.isSelected()) {
            tipo(4);
        }
        if (!txthoras.getText().isEmpty() && Integer.parseInt(txthoras.getText()) >= 10 && Integer.parseInt(txthoras.getText()) <= 60) {
            horasT++;
        }
        if (verificar == 0) {
            JOptionPane.showMessageDialog(null, "Faltan ingresar el nombre", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else if (!rbaux.isSelected() && !rbobs.isSelected() && !rbmed.isSelected() && !rbcir.isSelected()) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar el tipo de trabajador.", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else if (horasT == 0) {
            JOptionPane.showMessageDialog(null, "Error en horas trabajadas >=10 y <=60", "ERROR", JOptionPane.ERROR_MESSAGE);
            txthoras.requestFocus();
        } else {
            JOptionPane.showMessageDialog(null, "Datos validados", "CONFORME", JOptionPane.INFORMATION_MESSAGE);
            //btnIngresar.setEnabled(true);
            String nombres = txtnombres.getText();
            int horas = Integer.parseInt(txthoras.getText());
            cola3.offer(nombres, tipoGlobal, horas);
            btg.clearSelection();
            verTabla3(dtmEjercicio3);

            // txtATrabajadores.setText(cola3.print());
            // btnIngresar.setEnabled(false);
            txtnombres.setText("");
            txthoras.setText("");
            txtnombres.requestFocus();
            txtgastoTrabajadores.setText(String.valueOf(cola3.gastoTrabajadores()));
        }
    }//GEN-LAST:event_btnIngresar3ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Global.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Global().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar1;
    private javax.swing.JButton btnBuscar2;
    private javax.swing.JButton btnBuscar3;
    private javax.swing.JButton btnEliminar1;
    private javax.swing.JButton btnEliminar3;
    private javax.swing.JButton btnIngresar1;
    private javax.swing.JButton btnIngresar2;
    private javax.swing.JButton btnIngresar3;
    private javax.swing.JButton btnMayor3;
    private javax.swing.JButton btnPeek1;
    private javax.swing.JButton btnPeek2;
    private javax.swing.JButton btnPeek3;
    private javax.swing.JButton btnPoll1;
    private javax.swing.JButton btnPoll3;
    private javax.swing.JButton btnPop2;
    private javax.swing.JButton btnVer1;
    private javax.swing.JButton btnVer2;
    private javax.swing.JButton btningAuto1;
    private javax.swing.JButton btningAuto2;
    private javax.swing.JButton btningAuto3;
    private javax.swing.JTable dtm1;
    private javax.swing.JTable dtm2;
    private javax.swing.JTable dtm3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rbaux;
    private javax.swing.JRadioButton rbcir;
    private javax.swing.JRadioButton rbmed;
    private javax.swing.JRadioButton rbobs;
    private javax.swing.JTextField txtapellidos1;
    private javax.swing.JTextField txtapellidos2;
    private javax.swing.JTextField txtcorreo1;
    private javax.swing.JTextField txtcorreo2;
    private javax.swing.JTextField txtdireccion1;
    private javax.swing.JTextField txtdni1;
    private javax.swing.JTextField txtdni2;
    private javax.swing.JTextField txtgastoTrabajadores;
    private javax.swing.JTextField txthistoria2;
    private javax.swing.JTextField txthoras;
    private javax.swing.JTextField txtid1;
    private javax.swing.JTextField txtid2;
    private javax.swing.JTextField txtnombres;
    private javax.swing.JTextField txtnombres1;
    private javax.swing.JTextField txtnombres2;
    private javax.swing.JTextField txttelefono1;
    private javax.swing.JTextField txttelefono2;
    // End of variables declaration//GEN-END:variables
}
